---
nextcloud_enabled: false
nextcloud_available_externally: "false"

# directories
nextcloud_data_directory: "{{ docker_home }}/nextcloud"

# network
nextcloud_port: "8080"
nextcloud_hostname: "nextcloud"